### PR TITLE
Update the team information section

### PR DESCRIPTION
**Pull request by rossoskull**
Add team name and role of members.
screenshot from 2019-01-18 23-50-28

### CODE REVIEW

**Comment by aashutoshrathi** [comment]
@rossoskull Netlify is not configured properly on this repo.
Can you share a surge.sh link?

**Comment by rossoskull** [comment]
@aashutoshrathi here is the surge link.

https://salty-creature.surge.sh

**Review by aashutoshrathi — CHANGES_REQUESTED** [review]
Decrease Avatar Size and use Favicon as default

**Comment by rossoskull** [comment]
@aashutoshrathi I have made the changes. Let me know if I should decrease the avatar size more.

https://cute-reading.surge.sh

<blockquote><div><strong><a href="https://cute-reading.surge.sh/">Cerebro 2019</a></strong></div></blockquote>

**Review by aashutoshrathi — APPROVED** [review]

**Pull request merged**
