### PR TITLE
Integrate fullPage.js

### LINKED ISSUE #81: Integrate react-fullpage
On the index page. I think.

https://github.com/alvarotrigo/react-fullpage

### PR DESCRIPTION
**Pull request by rossoskull**
Fixes #81 
Currently, the Panel component's style isn't updated to suit the fullpage.

**Preview**
ezgif-4-bafde4f9b2cb

### CODE REVIEW

**Comment by DivyeshPuri** [comment]
@rossoskull It is not working correctly in mobile view. Please do check.

**Review by DivyeshPuri — COMMENTED** [review]
@rossoskull It is not working correctly in mobile view. Please do check.

**Review by aashutoshrathi — CHANGES_REQUESTED** [review]
@rossoskull Thanks for PR

Please address these:
- You might need to update your branch as per current master branch.
- Card sizes are changes for some reason.
- Also, you might need to disable overflow-x in Mobile view.
- Also, please add a permanent black background to fixed nav.
- And yeah as @DivyeshPuri said footer is missing in desktop view.

Also, welcome to the org, accept the invite.

**Review by DivyeshPuri — CHANGES_REQUESTED** [review]
Footer is also missing.

**Comment by aashutoshrathi** [comment]
Cards still have less width. :crying_cat_face:

**Comment by rossoskull** [comment]
@aashutoshrathi I have used uk's slider, as fullpage's slide wouldn't be a good option for small screens, styling is primitive, basics are implemented, and also threw in a nav bar.

**Comment by aashutoshrathi** [comment]
Will check @rossoskull

**Review by DivyeshPuri — CHANGES_REQUESTED** [review]
1. Auto slide missing
2. Arrows missing in the carousel
3. Fix card size in mobile view

**Comment by rossoskull** [comment]
@DivyeshPuri Made the changes.

**Review by DivyeshPuri — APPROVED** [review]
@rossoskull  Awesome work buddy 🎉 . @aashutoshrathi @anshumanv Review it.

**Review by anshumanv — APPROVED** [review]

**Review by aashutoshrathi — APPROVED** [review]

**Pull request merged**
