### PR TITLE
EventDetail Improved

### PR DESCRIPTION
**Pull request by Lucifer24**

### CODE REVIEW

**Comment by singhpratyush** [comment]
@Lucifer24: Please attach screenshots.

**Comment by anshumanv** [comment]
What did you improve exactly?

**Comment by anshumanv** [comment]
The team component that you made wasn't aligned with the mockups so it was discarded.

**Comment by Monal5031** [comment]
@Lucifer24 We are following exactly like the Mocks.

**Comment by Lucifer24** [comment]
What is did is changed the contact section like it is in mocks.

**Comment by Lucifer24** [comment]
There is also a need to change its position like it is in mocks.

**Comment by Lucifer24** [comment]
On the way to home, will post it asap.

**Comment by Lucifer24** [comment]
after

**Pull request closed without merging**
